export const menuItems = [
  {
    id: '1',
    title: 'Beyaynet',
    image: require('../assets/MenuImages/beyaynet.webp'),
    price: 280,
    description: 'A traditional Ethiopian vegetarian platter served on injera with an assortment of lentils, stews, and vegetables.',
    ingredients: ['Injera', 'Lentils', 'Split peas', 'Cabbage', 'Beets', 'Carrots', 'Potatoes', 'Spinach', 'Spices'],
  },
  {
    id: '2',
    title: 'Burger',
    image: require('../assets/MenuImages/burgers-sauteed.webp'),
    price: 350,
    description: 'A grilled beef burger with melted cheese, fresh vegetables, and house sauce in a soft toasted bun.',
    ingredients: ['Beef patty', 'Cheese', 'Lettuce', 'Tomato', 'Onions', 'Pickles', 'Burger bun', 'House sauce'],
  },
  {
    id: '3',
    title: 'Shiro',
    image: require('../assets/MenuImages/shiro.webp'),
    price: 11.0,
    description: 'A spicy Ethiopian chickpea stew, often served with injera and enjoyed as a hearty vegetarian meal.',
    ingredients: ['Chickpea flour', 'Onions', 'Garlic', 'Berbere spice', 'Oil', 'Water', 'Salt'],
  },
  {
    id: '4',
    title: 'Pizza',
    image: require('../assets/MenuImages/pizza.webp'),
    price: 450,
    description: 'Classic Italian-style pizza with tomato sauce, mozzarella cheese, and your choice of toppings.',
    ingredients: ['Pizza dough', 'Tomato sauce', 'Mozzarella cheese', 'Olive oil', 'Basil'],
  },
  {
    id: '5',
    title: 'Kitfo',
    image: require('../assets/MenuImages/Kitfo.webp'),
    price: 725,
    description: 'A beloved Ethiopian dish made with minced raw or lightly cooked beef mixed with spiced butter and mitmita.',
    ingredients: ['Minced beef', 'Niter kibbeh (spiced butter)', 'Mitmita (chili powder)', 'Salt'],
  },
  {
    id: '6',
    title: 'French fries',
    image: require('../assets/MenuImages/french-fries.webp'),
    price: 4.0,
    description: 'Golden, crispy French fries served hot and seasoned with a pinch of salt.',
    ingredients: ['Potatoes', 'Vegetable oil', 'Salt'],
  },
];
